CREATE TABLE IF NOT EXISTS books(
    id VARCHAR(50) NOT NULL UNIQUE,
    data JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);